// Code generated by MockGen. DO NOT EDIT.
// Source: internal/client/accrual_client.go
//
// Generated by this command:
//
//	mockgen -source=internal/client/accrual_client.go -destination=internal/client/mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	client "github.com/AlexeyKurlevsky/go-diploma/internal/client"
	gomock "go.uber.org/mock/gomock"
)

// MockAccrualClient is a mock of AccrualClient interface.
type MockAccrualClient struct {
	ctrl     *gomock.Controller
	recorder *MockAccrualClientMockRecorder
	isgomock struct{}
}

// MockAccrualClientMockRecorder is the mock recorder for MockAccrualClient.
type MockAccrualClientMockRecorder struct {
	mock *MockAccrualClient
}

// NewMockAccrualClient creates a new mock instance.
func NewMockAccrualClient(ctrl *gomock.Controller) *MockAccrualClient {
	mock := &MockAccrualClient{ctrl: ctrl}
	mock.recorder = &MockAccrualClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccrualClient) EXPECT() *MockAccrualClientMockRecorder {
	return m.recorder
}

// CheckOrder mocks base method.
func (m *MockAccrualClient) CheckOrder(ctx context.Context, orderNumber string) (*client.AccrualResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckOrder", ctx, orderNumber)
	ret0, _ := ret[0].(*client.AccrualResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckOrder indicates an expected call of CheckOrder.
func (mr *MockAccrualClientMockRecorder) CheckOrder(ctx, orderNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckOrder", reflect.TypeOf((*MockAccrualClient)(nil).CheckOrder), ctx, orderNumber)
}
